### PR TITLE
1925 Fix incorrect default column values in join tables

### LINKED ISSUE #1925: Fix vuu created and updated timestamp in join table
### Steps to Reproduce:
Use JoinsOfJoinsTableTest as example.
Create a join table, add a few rows. Delete a row. And when debugging we can see in JoinTable.processDelete , the index of keyToIndexMap is updated, but not indexToCreatedTime or indexToLastUpdatedTime. This means the timestamps are not showing correctly for each row.

Related to https://github.com/finos/vuu/issues/1909

### PR DESCRIPTION
**Pull request by tanjjj**
closes #1925 

Removed InnerJoin and use the timestamp from base table instead of the new timestamps for the join table.
Default columns for a join table is now passed in as joinColumns.

### CODE REVIEW

File: vuu/src/main/scala/org/finos/vuu/core/table/JoinTable.scala [hunk 1]
```diff
@@ -452,7 +445,10 @@ class JoinTable(val tableDef: JoinTableDef, val sourceTables: Map[String, DataTa
     if (keysByTable == null || !keyExistsInLeftMostSourceTable(key))
       EmptyRowData
     else {
-      val columnsByTable = viewPortColumns.getJoinColumnsByTable
+      var columnsByTable: Map[String, List[JoinColumn]] = viewPortColumns.getJoinColumnsByTable
+      if (includeDefaultColumns) {
```
Comment (stonesmi) [inline vuu/src/main/scala/org/finos/vuu/core/table/JoinTable.scala]: can we move this inside vp columns with a lazy val for performance reasons?

File: vuu/src/main/scala/org/finos/vuu/api/TableDef.scala [hunk 2]
```diff
@@ -223,7 +223,8 @@ class TableDef(val name: String,
                val permissionFunction: (ViewPort, TableContainer) => PermissionFilter = (_, _) => AllowAllPermissionFilter,
                val defaultSort: SortSpec = SortSpec(List.empty)) extends VuuInMemPluginLocator {
 
-  private val columns: Array[Column] = if (includeDefaultColumns) DefaultColumn.addDefaultColumns(customColumns) else customColumns
+  val defaultColumns: Array[Column] = if (includeDefaultColumns) DefaultColumn.getDefaultColumns(customColumns) else Array.empty
```
[the remark this answers is not in the document]
Comment (tanjjj) [reply vuu/src/main/scala/org/finos/vuu/api/TableDef.scala]: this is changed to private and we no longer need it outside this class

File: vuu/src/main/scala/org/finos/vuu/api/TableDef.scala [hunk 3]
```diff
@@ -281,13 +279,18 @@ case class JoinTableDef(
     visibility = visibility, permissionFunction = permissionFunction, defaultSort = defaultSort)
     with VuuInMemPluginLocator {
 
+  private val defaultColumnsAsJoinColumns: Array[Column] = if (includeDefaultColumns) Columns.fromColumns(this.baseTable, DefaultColumn.getDefaultColumns(customColumns)) else Array.empty
```
Comment (stonesmi) [inline vuu/src/main/scala/org/finos/vuu/api/TableDef.scala]: We could allow the developers to pass in the default columns and only call DefaultColumn.getDefaultColumns(customColumns) to add them if they aren't in the joinColumns already?

**Review by stonesmi — APPROVED** [review]
